<template>
  <span class="ti">
    <component v-if="iconComp" :is="iconComp" :stroke-width="strokeWidth" />
  </span>
</template>

<script setup>
import { computed } from 'vue'
import {
  IconGridDots, IconCalculator, IconChevronDown, IconSearch, IconSettings,
  IconMoodSmile, IconBell, IconCircleCheck, IconClockHour4, IconCheck, IconHelpCircle,
  IconPlayerPlay, IconLayoutDashboard, IconTool, IconX, IconPlus,
  IconCpu, IconSparkles, IconTrendingUp, IconTrendingDown, IconLink,
  IconShoppingCart, IconPackage, IconBuildingWarehouse, IconBuildingBank,
  IconCash, IconBuilding, IconUsers, IconFileInvoice, IconChartBar, IconBook,
  IconCalendar, IconClock, IconMinus, IconEye, IconEyeOff,
  IconAlertTriangle, IconInfoCircle, IconCircleX, IconChevronUp,
  IconFilter, IconDownload, IconUpload, IconRefresh, IconEdit, IconTrash,
  IconCopy, IconPaperclip,
  IconChevronLeft, IconChevronRight, IconChevronLeftPipe, IconChevronRightPipe,
  IconLoader2,
  IconWallet, IconBriefcase, IconList, IconCoin, IconFileCheck, IconDeviceDesktop,
  IconBuildingCommunity,
  IconHelp, IconDotsCircleHorizontal, IconMessageCircle,
  IconFileExport, IconFileImport,
  IconPencil, IconDots,
  IconHome,
  // ── Spa & Beauty icons ──
  IconScissors, IconHeart, IconDroplet, IconLeaf, IconFlower, IconHandStop,
  IconStar as IconStarFilled, IconSparkle,
  // ── QLNS / HR icons ──
  IconUserPlus, IconUserMinus, IconUserCheck, IconUserOff,
  IconIdBadge2, IconFileCertificate,
  IconTransfer, IconDoorExit,
  IconMedal, IconHeartHandshake,
  IconSitemap, IconLadder, IconDiamond,
  IconShirt, IconBulb, IconScale,
  // ── Extra common icons ──
  IconArrowsLeftRight, IconFilePlus,
  IconGift,
  IconStar, IconAward, IconReport,
  IconChartLine, IconChartDonut,
  IconSend, IconClipboardList, IconClipboardCheck,
  IconLock, IconLockOpen,
  IconMapPin, IconPhone, IconMail, IconAt,
  IconBuildingFactory, IconBuildingSkyscraper,
  IconFileText, IconFileDiff, IconFileAnalytics,
  IconUserCircle, IconUsersGroup,
  IconCheckbox, IconSquare,
  IconSortAscending, IconSortDescending,
  IconArrowUp, IconArrowDown, IconArrowLeft, IconArrowRight,
  IconExternalLink, IconMaximize, IconMinimize,
  IconCirclePlus, IconCircleMinus,
  IconDotsVertical,
  // ── DataTable header menu ──
  IconCircleOff,
  IconPinned, IconPinnedOff,
  IconTableColumn, IconColumnInsertLeft, IconColumnInsertRight, IconColumnRemove,
  IconTextWrap, IconTextWrapDisabled,
  // ── Form / misc ──
  IconKeyboard, IconPrinter,
  IconSun, IconMoon, IconApps, IconGrid3x3, IconBrandSlack,
  IconFolder, IconFolderOpen,
  IconLayoutKanban,
  IconFlag, IconFlag2, IconFlag3,
  // ── Weather ──
  IconCloud, IconWind, IconThermometer, IconDroplets,
  // ── Task form extras ──
  IconTag, IconUser, IconRepeat, IconGitBranch, IconAlignLeft,
  IconTable,
  IconFingerprint,
} from '@tabler/icons-vue'

const props = defineProps({
  name:        { type: String, required: true },
  strokeWidth: { type: [Number, String], default: 1.5 },
})

const MAP = {
  // ── Layout & Navigation ──
  'grid-dots':              IconGridDots,
  'layout-dashboard':       IconLayoutDashboard,
  'home':                   IconHome,
  'list':                   IconList,
  'sitemap':                IconSitemap,
  'ladder':                 IconLadder,

  // ── Chevron / Arrow ──
  'chevron-down':           IconChevronDown,
  'chevron-up':             IconChevronUp,
  'chevron-left':           IconChevronLeft,
  'chevron-right':          IconChevronRight,
  'chevron-left-pipe':      IconChevronLeftPipe,
  'chevron-right-pipe':     IconChevronRightPipe,
  'arrow-up':               IconArrowUp,
  'arrow-down':             IconArrowDown,
  'arrow-left':             IconArrowLeft,
  'arrow-right':            IconArrowRight,
  'arrows-left-right':      IconArrowsLeftRight,
  'transfer':               IconTransfer,

  // ── User & HR ──
  'users':                  IconUsers,
  'users-group':            IconUsersGroup,
  'user-circle':            IconUserCircle,
  'user-plus':              IconUserPlus,
  'user-minus':             IconUserMinus,
  'user-check':             IconUserCheck,
  'user-off':               IconUserOff,
  'id-badge-2':             IconIdBadge2,
  'door-exit':              IconDoorExit,
  'medal':                  IconMedal,
  'heart-handshake':        IconHeartHandshake,
  'diamond':                IconDiamond,
  'shirt':                  IconShirt,
  'bulb':                   IconBulb,
  'scale':                  IconScale,
  'award':                  IconAward,
  'gift':                   IconGift,

  // ── File & Document ──
  'file-invoice':           IconFileInvoice,
  'file-check':             IconFileCheck,
  'file-certificate':       IconFileCertificate,
  'file-export':            IconFileExport,
  'file-import':            IconFileImport,
  'file-plus':              IconFilePlus,
  'file-text':              IconFileText,
  'file-diff':              IconFileDiff,
  'file-analytics':         IconFileAnalytics,
  'clipboard-list':         IconClipboardList,
  'clipboard-check':        IconClipboardCheck,
  'report':                 IconReport,

  // ── Finance & Business ──
  'calculator':             IconCalculator,
  'cash':                   IconCash,
  'coin':                   IconCoin,
  'wallet':                 IconWallet,
  'building-bank':          IconBuildingBank,
  'building':               IconBuilding,
  'building-warehouse':     IconBuildingWarehouse,
  'building-community':     IconBuildingCommunity,
  'building-factory':       IconBuildingFactory,
  'building-skyscraper':    IconBuildingSkyscraper,
  'briefcase':              IconBriefcase,
  'shopping-cart':          IconShoppingCart,
  'package':                IconPackage,

  // ── Chart & Data ──
  'chart-bar':              IconChartBar,
  'chart-line':             IconChartLine,
  'chart-donut':            IconChartDonut,
  'trending-up':            IconTrendingUp,
  'trending-down':          IconTrendingDown,

  // ── Action ──
  'plus':                   IconPlus,
  'minus':                  IconMinus,
  'x':                      IconX,
  'check':                  IconCheck,
  'search':                 IconSearch,
  'filter':                 IconFilter,
  'settings':               IconSettings,
  'refresh':                IconRefresh,
  'edit':                   IconEdit,
  'pencil':                 IconPencil,
  'trash':                  IconTrash,
  'copy':                   IconCopy,
  'download':               IconDownload,
  'upload':                 IconUpload,
  'eye':                    IconEye,
  'eye-off':                IconEyeOff,
  'lock':                   IconLock,
  'lock-open':              IconLockOpen,
  'external-link':          IconExternalLink,
  'maximize':               IconMaximize,
  'minimize':               IconMinimize,
  'sort-ascending':         IconSortAscending,
  'sort-descending':        IconSortDescending,
  'send':                   IconSend,

  // ── Status & Indicator ──
  'circle-check':           IconCircleCheck,
  'circle-x':               IconCircleX,
  'circle-plus':            IconCirclePlus,
  'circle-minus':           IconCircleMinus,
  'alert-triangle':         IconAlertTriangle,
  'info-circle':            IconInfoCircle,
  'star':                   IconStar,
  'checkbox':               IconCheckbox,
  'square':                 IconSquare,

  // ── DataTable header menu ──
  'circle-off':             IconCircleOff,
  'pinned':                 IconPinned,
  'pinned-off':             IconPinnedOff,
  'table-column':           IconTableColumn,
  'column-insert-left':     IconColumnInsertLeft,
  'column-insert-right':    IconColumnInsertRight,
  'column-remove':          IconColumnRemove,
  'text-wrap':              IconTextWrap,
  'text-wrap-disabled':     IconTextWrapDisabled,

  // ── UI & Misc ──
  'dots':                   IconDots,
  'dots-vertical':          IconDotsVertical,
  'dots-circle-horizontal': IconDotsCircleHorizontal,
  'paperclip':              IconPaperclip,
  'link':                   IconLink,
  'book':                   IconBook,
  'calendar':               IconCalendar,
  // ── Spa & Beauty ──
  'scissors':               IconScissors,
  'heart':                  IconHeart,
  'droplet':                IconDroplet,
  'leaf':                   IconLeaf,
  'flower':                 IconFlower,
  'hand-stop':              IconHandStop,
  'sparkle':                IconSparkle,
  'clock':                  IconClock,
  'clock-hour-4':           IconClockHour4,
  'fingerprint':            IconFingerprint,
  'loader-2':               IconLoader2,
  'bell':                   IconBell,
  'mood-smile':             IconMoodSmile,
  'player-play':            IconPlayerPlay,
  'tool':                   IconTool,
  'cpu':                    IconCpu,
  'sparkles':               IconSparkles,
  'device-desktop':         IconDeviceDesktop,
  'help':                   IconHelp,
  'help-circle':            IconHelpCircle,
  'message-circle':         IconMessageCircle,
  'map-pin':                IconMapPin,
  'phone':                  IconPhone,
  'mail':                   IconMail,
  'at':                     IconAt,
  'keyboard':               IconKeyboard,
  'printer':                IconPrinter,
  'sun':                    IconSun,
  'moon':                   IconMoon,
  'apps':                   IconApps,
  'grid-3x3':               IconGrid3x3,
  'folder':                 IconFolder,
  'folder-open':            IconFolderOpen,
  'layout-kanban':          IconLayoutKanban,
  'flag':                   IconFlag,
  'flag-2':                 IconFlag2,
  'flag-3':                 IconFlag3,
  // ── Weather ──
  'cloud':                  IconCloud,
  'wind':                   IconWind,
  'thermometer':            IconThermometer,
  'droplets':               IconDroplets,
  // ── Task form extras ──
  'tag':                    IconTag,
  'user':                   IconUser,
  'repeat':                 IconRepeat,
  'git-branch':             IconGitBranch,
  'align-left':             IconAlignLeft,
  'table':                  IconTable,
}

const iconComp = computed(() => {
  const key = props.name.replace(/^ti-/, '')
  return MAP[key] || null
})
</script>
